---
title: "p03_modeling"
author: "okura"
output: html_document
date: "2023-10-25"
editor_options: 
  chunk_output_type: console
---

# load package
```{r}
require(tidyverse)
require(lubridate)
require(survival)
require(nlme)
require(JM)
require(openxlsx)
require(officer)
require(survivalROC)
require(ggpubr)
```

# definition; ggsave2_tri, sv2ggkm
```{r}

outputdir <- "./figs/"
if(!dir.exists(outputdir)){
  dir.create(outputdir)
}

ggsave2_tri <- function(plot, wid = 9, hei=9){
  plot_name <- deparse(substitute(plot))
  
  #png
  file_name <- paste(outputdir,plot_name, ".png", sep = "",collapse = "")
  ggsave(filename = file_name,plot = plot,device = "png",width = wid, height = hei,dpi = 300,units = "cm")
  
  
  #pdf
  file_name <- paste(outputdir,plot_name, ".pdf", sep = "",collapse = "")
  # ggsave(filename = file_name,plot = plot,device = "pdf",width = wid, height = hei,dpi = 300,units = "cm")
  
  #pptx
  file_name <- paste(outputdir,plot_name, ".pptx", sep = "",collapse = "")
  plot_ed <- rvg::dml(ggobj = plot,width = wid, height = hei)
  
  doc <- read_pptx() %>%
    add_slide('Title and Content', 'Office Theme') %>%
    ph_with(value = "", location = ph_location_type(type = "title")) %>%
    ph_with(value = plot_ed, location = ph_location(type = "body",width = cm2inch(wid), height = cm2inch(hei),left = 2, top = 2))
  doc %>%
    print(target = file_name)
}

inch2cm <- function(x){
  return(x/0.39370)
}
cm2inch <- function(x){
  return(0.39370*x)
}

p2cm <- function(x){
  return(as.integer(0.008466666666666667 * x))
}

cm2p <- function(x){
  return(as.integer(118.11023622047244 *x))
}

sv2ggkm <- function(svfit, df){
  p <- ggsurvplot(fit = svfit, data = df,
                risk.table.title = "risk.table.title", risk.table.y.text.col = TRUE,
           risk.table.y.text = FALSE, fontsize = 5,
           risk.table = TRUE, tables.theme = theme_pubr(), ggtheme = theme_pubr())
  p_km <- p$plot
  p_tb <- p$table
  p2 <- cowplot::plot_grid(p_km, p_tb, ncol = 1,align = "v", rel_heights = c(3,1))
  grid::grid.draw(p2)
  return(p2)
}
```

# timestamp
```{r}
ts <- Sys.time()  %>% 
    as.character() %>% 
    str_remove_all(., "[-:]*") %>% 
    str_replace(.," ", "_")
ts
```


# read each file
```{r}
f_cox_rds <- "../p03_modeling/df_cox_20231129_044447.rds"
f_mix_rds <- "../p03_modeling/df_mix_20231129_044447.rds"

fix_df <- function(df){
  df %>% 
    mutate(Stage = factor(cStage_fix, levels=c("I", "II", "III", "IV")) %>% 
             as.numeric()) %>%
    mutate(is_well = if_else(is.na(diffgrade_fix), "",as.character(diffgrade_fix))  %>%
             magrittr::equals("well")) %>%
    mutate(is_right = position_fix == "right_side"|position_fix == "multiple") %>% 
    mutate(gender = if_else(gender == "1",1, 0 )) %>% 
    return()
}

df_cox <- readRDS(f_cox_rds) %>%
  fix_df()

df_mix <- readRDS(f_mix_rds) %>%
  fix_df() %>% 
  filter(CEA != 0) %>% 
  filter(CEA != is.na(CEA))
```

# cox proportional hazards model 
```{r}
df_mix_1st <- df_mix %>%
    group_by(id) %>%
    filter(year_samp_from_start == min(year_samp_from_start)) %>%
    ungroup()

fit_cox <- coxph(Surv(time = time_y, event = event) ~ age_at_start + Stage + is_well + gender + is_right + log2(CEA),
                 data = df_mix_1st, x = TRUE)

summary(fit_cox)

exp(confint(fit_cox, level = 0.95, process = "Event"))
```

# mixed effects model
```{r}
df_mix_cea <- df_mix %>% 
    filter(CEA != is.na(CEA)) %>% 
    filter(CEA != 0) %>% 
    mutate(year_samp_from_start = if_else(year_samp_from_start == 0, 12/(365.25*24), year_samp_from_start)) %>% 
    rename(inj_OHP = `inj_L-OHP`) %>% 
    filter(year_samp_from_start < time_y)

vcol_in <- df_mix_cea %>%
    colnames() %>%
    .[str_detect(., "^inj_|^prs_")]

for (v in vcol_in){
    print(v)
    df_mix_cea[[v]] <- log2(df_mix_cea[[v]] +1)
}

inj_col <- str_subset(colnames(df_mix_cea), pattern="inj_") %>% 
          setdiff(c("inj_HER"))
inj_all <- str_c(inj_col, collapse = " + ") 

prs_col <- str_subset(colnames(df_mix_cea), pattern="prs_")
prs_all <- str_c(prs_col, collapse = " + ")

si_col <- str_subset(colnames(df_mix_cea), pattern="si_")
si_all <- str_c(si_col, collapse = " + ")

# inj_all
# prs_all
# si_all

fit_mix_cea <- lme(log2(CEA) ~ year_samp_from_start +
        inj_Nivo + inj_OHP + inj_FU_LV + inj_IRI + inj_Pmab + inj_Bev + inj_Cmab + inj_AFL + inj_Rmab + inj_Pembro + 
        prs_TS1 + prs_Cape + prs_REG + prs_TAS102 + prs_UFT + prs_BINI +
        si_colrec_sx + si_endo_tx + si_liv_sx + si_lng_sx + si_rtx, 
        random = ~ year_samp_from_start|id, data = df_mix_cea, control = lmeControl(opt = "optim"))

summary(fit_mix_cea)$coef$fixed

```

# Joint model
```{r}
fit_cox_sub <- coxph(Surv(time = time_y, event = event) ~ age_at_start + Stage + is_well + gender + is_right, 
                     data = df_cox, x = TRUE)

fit_JM_cea <- jointModel(fit_mix_cea, fit_cox_sub, 
                         timeVar = "year_samp_from_start",
                         method = "weibull-PH-aGH")

summary(fit_JM_cea)

exp(confint(fit_JM_cea, level = 0.95, process = "Event"))
```

# load and save functions
```{r}
# save function
append_list <- function(l, x){
  xname  <- deparse(substitute(x))
  l[[xname]] <- x
  return(l)
}

# load function
get_vals <- function(l){
  lnames <- names(l)
  for(n in lnames){
    assign(n, l[[n]], pos = .GlobalEnv)
  }
  return(lnames)
}

eval_list <- list() %>% 
  append_list(df_mix_1st) %>% 
  append_list(fit_cox) %>% 
  append_list(df_cox) %>% 
  append_list(df_mix_cea) %>% 
  append_list(fit_cox_sub) %>% 
  append_list(fit_mix_cea) %>% 
  append_list(fit_JM_cea)
  
f_eval_list <- c("../p03_modeling/dat/eval_list_",ts, ".rds") %>% 
  str_c(collapse = "")
f_eval_list

saveRDS(eval_list, file = f_eval_list)
```

```{r}
sessionInfo()
```

