---
title: "p05_validation"
author: "fk506cni/okura"
date: "2023-11-05"
output: html_document
editor_options: 
  chunk_output_type: console
---

# load package
```{r}
require(tidyverse)
require(lubridate)
require(survival)
require(nlme)
require(JM)
require(openxlsx)
require(officer)
require(survivalROC)
require(ggpubr)
require(rsample)
```

# definition; ggsave2_tri, sv2ggkm
```{r}

outputdir <- "./figs/"
if(!dir.exists(outputdir)){
  dir.create(outputdir)
}

ggsave2_tri <- function(plot, wid = 9, hei=9){
  plot_name <- deparse(substitute(plot))
  
  #png
  file_name <- paste(outputdir,plot_name, ".png", sep = "",collapse = "")
  ggsave(filename = file_name,plot = plot,device = "png",width = wid, height = hei,dpi = 300,units = "cm")
  
  
  #pdf
  file_name <- paste(outputdir,plot_name, ".pdf", sep = "",collapse = "")

  #pptx
  file_name <- paste(outputdir,plot_name, ".pptx", sep = "",collapse = "")
  plot_ed <- rvg::dml(ggobj = plot,width = wid, height = hei)
  
  doc <- read_pptx() %>%
    add_slide('Title and Content', 'Office Theme') %>%
    ph_with(value = "", location = ph_location_type(type = "title")) %>%
    ph_with(value = plot_ed, location = ph_location(type = "body",width = cm2inch(wid), height = cm2inch(hei),left = 2, top = 2))
  doc %>%
    print(target = file_name)
}

inch2cm <- function(x){
  return(x/0.39370)
}
cm2inch <- function(x){
  return(0.39370*x)
}

p2cm <- function(x){
  return(as.integer(0.008466666666666667 * x))
}

cm2p <- function(x){
  return(as.integer(118.11023622047244 *x))
}

sv2ggkm <- function(svfit, df){
  p <- ggsurvplot(fit = svfit, data = df,
                risk.table.title = "risk.table.title", risk.table.y.text.col = TRUE,
           risk.table.y.text = FALSE, fontsize = 5,
           risk.table = TRUE, tables.theme = theme_pubr(), ggtheme = theme_pubr())
  p_km <- p$plot
  p_tb <- p$table
  p2 <- cowplot::plot_grid(p_km, p_tb, ncol = 1,align = "v", rel_heights = c(3,1))
  grid::grid.draw(p2)
  return(p2)
}
```

# load and save functions
```{r}
append_list <- function(l, x){
  xname  <- deparse(substitute(x))
  l[[xname]] <- x
  return(l)
}


# load function
get_vals <- function(l){
  lnames <- names(l)
  for(n in lnames){
    assign(n, l[[n]], pos = .GlobalEnv)
  }
  return(lnames)
}
```

# definition; timestamp
```{r}
ts <- Sys.time()  %>% 
    as.character() %>% 
    str_remove_all(., "[-:]*") %>% 
    str_replace(.," ", "_")
ts
```


```{r}
f_rds <- "../p03_modeling/dat/eval_list_20240702_083021.206594.rds"
readRDS(f_rds) %>%
  get_vals()
```


```{r}
df_mix_smr <- df_mix_cea %>% 
  dplyr::select(id, matches("^(inj|prs|si)_")) %>%
  mutate_at(vars(matches("^(inj|prs|si)_")), ~if_else(. >0, 1, 0)) %>%
  group_by(id) %>% 
  summarise(across(matches("^(prs|inj|si)_"), max)) %>%
  pivot_longer(cols = -id) %>%
  group_by(name) %>%
  summarise(n=n(),
            user=sum(value)) %>% 
  rename(variable = name) %>% 
  rename(total = n) %>% 
  mutate(percentage = 100*round(user/total, digits = 3))

print(df_mix_smr, n=22)

f_cross_valid <- "../p05_cross_validation/cross_valid_tsxx.xlsx" %>% 
  str_replace("tsxx", ts)

f_cross_valid

# write.xlsx(x = df_mix_smr, file = f_cross_valid, overwrite = T)
```

```{r}
sessionInfo()
```

